service: analysis-service
frameworkVersion: ">=1.30.0"
custom:
  bucket: ${env:CHAPTER2_BUCKET}
  region: ${env:AWS_DEFAULT_REGION, 'eu-west-1'}
  accountid: ${env:AWS_ACCOUNT_ID}

provider:
  name: aws
  runtime: nodejs12.x
  region: ${env:AWS_DEFAULT_REGION, 'eu-west-1'}
  memorySize: 512
  timeout: 10
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "rekognition:*"
      Resource: "*"

functions:
  analyzeImages:
    handler: handler.analyzeImages
    environment:
      BUCKET: ${self:custom.bucket}
      REGION: ${self:custom.region}
      ACCOUNTID: ${self:custom.accountid}

