service: c6p-classify
frameworkVersion: ">=1.30.0"
plugins:
  - serverless-dotenv-plugin
custom:
  region: ${env:AWS_DEFAULT_REGION, 'eu-west-1'}
  accountid: ${env:AWS_ACCOUNT_ID}
  dotenv:
    path: ../.env

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ${env:AWS_DEFAULT_REGION, 'eu-west-1'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"
    - Effect: Allow
      Action:
        - comprehend:DetectSentiment
        - comprehend:StartDocumentClassificationJob
        - comprehend:DescribeDocumentClassificationJob
      Resource: "*"
    - Effect: Allow
      Action:
        - sts:AssumeRole
      Resource:
        - ${env.CHAPTER6_DATA_ACCESS_ARN}
    - Effect: Allow
      Action:
        - iam:PassRole
      Resource: "*"

functions:
  classify:
    handler: handler.classify
  poll:
    handler: handler.poll
  cleanup:
    handler: handler.cleanup
